# Core paths to monitor
/boot                   NORMAL
/bin                    NORMAL
/sbin                   NORMAL
/lib                    NORMAL
/lib64                  NORMAL
/usr/bin               NORMAL
/usr/sbin              NORMAL
/usr/lib               NORMAL
/usr/lib64             NORMAL
/etc                    PERMS+FTYPE+INO

# DevOps-friendly exclusions
!/var/lib/docker/
!/var/lib/containers/
!/var/lib/toolbox/
!/home/*/workspace/
!/home/*/.cache/
!/tmp/
!/var/tmp/
!/var/log/
